import React, { useMemo } from 'react';
import { useProjectStore } from '../../store/projectStore.ts';
import { generatePattern } from '../../core/freesewingAdapter.ts';

/* ==========================================================================
   GarmentPreview — FreeSewing-Powered Pattern Preview

   Renders a REAL pattern generated by FreeSewing's Brian block.
   The SVG output from FreeSewing is displayed directly, giving an accurate
   technical flat of the actual pattern pieces that will be used for the
   crochet grid.

   Falls back gracefully if FreeSewing throws an error (e.g. invalid
   measurements), showing a placeholder message instead.
   ========================================================================== */

export const GarmentPreview: React.FC = () => {
  const style = useProjectStore((s) => s.style);
  const size = useProjectStore((s) => s.size);
  const customMeasurements = useProjectStore((s) => s.customMeasurements);
  const ease = useProjectStore((s) => s.ease);
  const necklineDepth = useProjectStore((s) => s.necklineDepth);
  const necklineWidth = useProjectStore((s) => s.necklineWidth);
  const sleeveWidth = useProjectStore((s) => s.sleeveWidth);

  // Generate pattern via FreeSewing — memoized on all inputs
  const result = useMemo(() => {
    try {
      return {
        patternSet: generatePattern(
          size,
          style,
          customMeasurements,
          ease,
          necklineDepth,
          necklineWidth,
          sleeveWidth,
        ),
        error: null,
      };
    } catch (err) {
      console.error('[GarmentPreview] Pattern generation error:', err);
      return {
        patternSet: null,
        error: err instanceof Error ? err.message : 'Pattern generation failed',
      };
    }
  }, [size, style, customMeasurements, ease, necklineDepth, necklineWidth, sleeveWidth]);

  const { patternSet, error } = result;
  const hasSvg = patternSet?.svgString && patternSet.svgString.length > 0;
  const pieceCount = patternSet?.pieces.length ?? 0;
  const pieceNames = patternSet?.pieces.map((p) => p.name).join(', ') ?? '';

  return (
    <div className="gp-wrap">
      {/* ---- Pattern paper container ---- */}
      <div className="gp-paper">
        {hasSvg ? (
          <div
            className="gp-svg-container"
            dangerouslySetInnerHTML={{ __html: patternSet!.svgString }}
          />
        ) : (
          /* ---- Fallback when no SVG available ---- */
          <div className="gp-fallback">
            <svg
              width="48"
              height="48"
              viewBox="0 0 48 48"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <rect x="8" y="6" width="32" height="36" rx="2" opacity="0.3" />
              <path d="M16 14 L24 10 L32 14 L32 34 L16 34 Z" opacity="0.5" />
              <line x1="24" y1="16" x2="24" y2="30" strokeDasharray="2 2" opacity="0.3" />
            </svg>
            <p className="gp-fallback-text">
              {error
                ? `⚠ ${error}`
                : 'Pattern preview will appear as you configure your garment'}
            </p>
          </div>
        )}
      </div>

      {/* ---- Piece count summary ---- */}
      {pieceCount > 0 && (
        <p className="gp-piece-count">
          {pieceCount} piece{pieceCount !== 1 ? 's' : ''}: {pieceNames}
        </p>
      )}

      {/* ---- Scoped styles ---- */}
      <style>{`
        .gp-wrap {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: var(--space-3, 12px);
          width: 100%;
        }

        .gp-paper {
          width: 100%;
          max-width: 340px;
          min-height: 280px;
          background:
            radial-gradient(circle at 6px 6px, rgba(200,195,188,0.18) 0.7px, transparent 0.7px);
          background-size: 12px 12px;
          background-color: #f8f7f5;
          border-radius: 8px;
          border: 1px solid rgba(0,0,0,0.06);
          padding: 16px;
          display: flex;
          align-items: center;
          justify-content: center;
          overflow: hidden;
          box-shadow:
            0 1px 3px rgba(0,0,0,0.04),
            0 4px 12px rgba(0,0,0,0.02);
        }

        .gp-svg-container {
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        /* Style the FreeSewing SVG to fill the container */
        .gp-svg-container > svg {
          width: 100%;
          height: auto;
          max-height: 400px;
        }

        /* Override FreeSewing's default stroke styles for our dark-on-light preview */
        .gp-svg-container .fabric {
          stroke: #3a3632;
          stroke-width: 0.8;
          fill: none;
        }
        .gp-svg-container .fabric.sa {
          stroke: #9a9590;
          stroke-width: 0.4;
          stroke-dasharray: 4 2;
        }
        .gp-svg-container .various {
          stroke: #b0aaa4;
          stroke-width: 0.5;
        }
        .gp-svg-container .contrast {
          stroke: #c0bab4;
        }
        .gp-svg-container .help {
          stroke-width: 0.3;
          stroke-dasharray: 3 2;
        }
        .gp-svg-container .center {
          text-anchor: middle;
        }
        .gp-svg-container text {
          font-family: 'Inter', system-ui, sans-serif;
          font-size: 4px;
          fill: #9a9590;
        }
        .gp-svg-container .mark {
          stroke: #b0aaa4;
          stroke-width: 0.4;
        }
        .gp-svg-container .dotted {
          stroke-dasharray: 1 2;
        }
        .gp-svg-container .dashed {
          stroke-dasharray: 4 2;
        }

        .gp-fallback {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 12px;
          padding: 32px 16px;
          color: #9a9590;
          text-align: center;
        }
        .gp-fallback-text {
          font-size: 12px;
          line-height: 1.5;
          max-width: 220px;
          margin: 0;
          color: #9a9590;
        }

        .gp-piece-count {
          font-size: 11px;
          color: var(--color-text-tertiary, #9a9590);
          text-align: center;
          margin: 0;
          letter-spacing: 0.02em;
        }
      `}</style>
    </div>
  );
};
